---
- name: Include Debian tasks
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include RHEL tasks
  include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"

- name: Ensure Docker service is enabled and started
  ansible.builtin.systemd:
    name: "{{ docker_service_name }}"
    enabled: true
    state: started
